# Generated by Django 5.1.4 on 2024-12-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='title',
        ),
        migrations.AddField(
            model_name='challenge',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('date', models.DateField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
            ],
        ),
    ]
